//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// Created via this command line: "C:\Users\A261620\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://altkomvolvo1.api.crm4.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Altkom.Volvo.User4.Plugin" /out:"C:\Users\A261620\AppData\Roaming\MscrmTools\XrmToolBox\Settings\CrmSvcUtil Ref\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"user4@altkomvolvo1.onmicrosoft.com" /password:"*********" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Altkom.Volvo.User4.Plugin
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8676")]
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Altkom.Volvo.User4.Plugin.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Altkom.Volvo.User4.Plugin.Account> AccountSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Altkom.Volvo.User4.Plugin.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Altkom.Volvo.User4.Plugin.alt_alt_user4"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Altkom.Volvo.User4.Plugin.alt_alt_user4> alt_alt_user4Set
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Altkom.Volvo.User4.Plugin.alt_alt_user4>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Altkom.Volvo.User4.Plugin.alt_user4contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Altkom.Volvo.User4.Plugin.alt_user4contact> alt_user4contactSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Altkom.Volvo.User4.Plugin.alt_user4contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Altkom.Volvo.User4.Plugin.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Altkom.Volvo.User4.Plugin.Contact> ContactSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Altkom.Volvo.User4.Plugin.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Altkom.Volvo.User4.Plugin.Opportunity"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Altkom.Volvo.User4.Plugin.Opportunity> OpportunitySet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<Altkom.Volvo.User4.Plugin.Opportunity>();
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
}